### ISSUE TITLE
Shorten the value of resistance and capacitance

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/core#142]
Here the Resistance should be `100k` and capacitance could be `0.1uF` 

![Image](https://github.com/user-attachments/assets/c25d96cd-73b6-4a2e-8469-8ff91940a844)

**Comment by imrishabh18** [comment]
@seveibar Currently, what I am doing in `circuit-to-svg` is looping through the circuit-json again to match the `source_component_id` and then get the name and value. A better way would be having these value in the `schematic_component` itself, we can reduce that extra loop to get the value What do you think?

![Image](https://github.com/user-attachments/assets/f43a3a71-9f82-429d-8c68-30505b3d7d1c)
![Image](https://github.com/user-attachments/assets/be979ace-7ee8-4f2f-845f-d432c7df17a1)

**Comment by seveibar** [comment]
The loop is fine! Note that if you use soup-util eventually it will automatically index to avoid looping

**Comment by imrishabh18** [comment]
So, you mean to add this new `display_value` in the `source_component` itself?
