### ISSUE TITLE
Add support for <transistor />

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#146]

**Comment by ShiboSoftwareDev** [comment]
@seveibar I need this for the wifi camera module, it's the only missing part
![Image](https://github.com/user-attachments/assets/ce5787a9-4fb7-4487-98d7-9656a2396459)

**Comment by ShiboSoftwareDev** [comment]
CC @Anshgrover23

**Comment by Anshgrover23** [comment]
@ShiboSoftwareDev ok i will try to do that. As I have made two prs in props and circuit-json , I will start work on it tomorrow.
