### ISSUE TITLE
Errors in `circuit-to-svg` when doing `toMatchSchematicSnapshot` in `battery.test.tsx` - undefined is not an object (evaluating 'symbol.primitives')

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#178]
![Image](https://github.com/user-attachments/assets/9ed24702-ecd3-43d9-8b0b-c0ebf4f87bf9)

**Comment by Abse2001** [comment]
@seveibar I will close this after updating circuit-to-svg and core

**Comment by Abse2001** [comment]
Commit #182
