### ISSUE TITLE
Bug: `pcbRotation` not impacting output `cad_component` rotation on resistor

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#221]
![Image](https://github.com/user-attachments/assets/1eda91b1-05f1-467b-aa6d-5485f2a114b1)

https://snippets.tscircuit.com/editor?&snippet_type=package#data:application/gzip;base64,H4sIAOceJGcAA52U226cMBCG73mKka9YKbCwJ2gUoqpsUlVK0hVNT1cVAYeidrFlzKoV4t0znCHsKlHu7PE/3/zjMcR7zoSEHLKUejS8oSEU8CjYHsh7mQbxPKUHGj/4Qhc01P7SkCjDlPvdF2u1Mczd1vvmnc6MtPVBk0xbHjR3YS+tlWGNOR5N41QycVZuXJ/7QYy7MVAEWSznAROUKAr9VyUHLEkl3P53f8ccHFC5YDw9R2bi7+k5pFLESQTFDJxLyBVo9Lvvnonq5/5VUh6QWafzNrWqdacSb0POkC6qgJ8EWIOYtxh7ZExyLCYxYKyMBcGiPceacKwpZ2EYf14k2ROSfcTRixy36ay7apW4dWvDtMDnhm2sMY6rUtfyjex6jGsaHOLqDt+Eu7naNvOpn6RKyggOBhWCykwkoOIS4CISLOOX1Rp35fiaNQAPHn44+aoYBjwmfRmzxCHvjJBGpDu7unNIQqV+WA9iuzoWJfjo2+CnI8LPX++b4PLXsg3PO1f4imovVnHMA/A4MZ289K4jqRhmWqPMn05u6uuRwB4TTbtBjrO0Ja7KKr3LAQTfAmdp1xYkNOobHx8NkiprpyqjybpyWRgBubfR0cCieAbvedXI25ENbE/N5J7dsDC7TZfCD2j1s2hu8vpDAZINCvelTmutUmue0tbHiELtsRYm3I9321eJXUvHNl8rxTvopaNZXsy7z2GmFMoTFJB4HdsFAAA=

**Comment by imrishabh18** [comment]
@seveibar The rotation currently rotates the copper pads of the board, and not the whole 3d-model. Take a look here

https://snippets.tscircuit.com/editor?&snippet_type=board#data:application/gzip;base64,H4sIAPmfKGcAA52UW2+bQBCF3/kVo30iUsDgGzQKUVWcVJWS1KLp7anCsMGr1ixa1m4rxH/vAIsBX5Sob+zZM9+cYRfYJuNCQgHbnAY0vqcxlPAs+AbIW5lHbJTTHWWrUJiCxsYvGhOtX/K0/ORM55a9XARfgvOViTHbGZIbk53hj92JM7WcISegOcslF5fVwg+zMGK4GgJFtGVyFHFBiabRP3VxxNNcwsNff80y8EDPBM/yK2Sm4YZeQS4FSxMoL8C7gUID5V9+DWx0H+bXSbVBLva+YN642nQ6CebkEumiFsI0wh7EfkDtmXOZYTOJgjW1xgSbdhzniOMcc8aW9fNFkntEck8kepHjq8n2r1onfjNavywKM8u1ZqjjU+Vr+db2bohTA/ZxzYT/hbu/Xajzaa6kTiqlPhhB5VakoOMjwPWKhyKG3yyWaw8xmw2BNWXJWqrVTW1DY3Ww6hkgi1bfvGJa9oWAy1AynnrkjRXThOz3bh89klJp7mY9bdloSYqfQyt+OGH8+PlJiZMfk1Ye7VPh/WqyOOUgQ6FCoMpS2yuq9Cayyn6tM6j97hW2ORsY3OFctlszD6uMierS5exB8J5kPN8PBilNutGHW72iOtq5zhiy6Vw1RkARzE0MMC4P4B2vvg7tofViH4cpAlexsLotlyKMaP0jUW/y7l0Jkvcad63Oe53Ka5/zNtuIQu+pEY647x8XrzL7joljvtaK76CzDs7yelR/K9XiQiu1fxbIQPf3BQAA

So, what is the expected outcome when we have `group` and not `board` on rotation?

**Comment by seveibar** [comment]
The 3d model is supposed to rotate to match the pads.
