### ISSUE TITLE
Pin label normalizer , add underscore when enumerating suffix

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/core#265]
Test file - `chip-pin-alias.test.tsx` 

I think this test in particular points to a very confusing behavior from the normalizer. `B11` and `B112` should probably be `B1_1` and `B1_2`

**Comment by anas-sarkez** [comment]
@imrishabh18  this issue needs to close
  ![Image](https://github.com/user-attachments/assets/3d515473-0f25-4fd6-a13d-cdb55762faae)

**Comment by imrishabh18** [comment]
Thanks for pointing out!
