### ISSUE TITLE
Pin arrangement issue in schematic

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/core#280]
https://tscircuit.com/imrishabh18/C141517

Total pins should have been 24 and equally distributed on both the sides, like the image attached below.

## Correct Version

![Image](https://github.com/user-attachments/assets/20130119-d6a4-4535-9164-24425798e55c)

## Incorrect Version

Why is there pin 25?

![Image](https://github.com/user-attachments/assets/4b56e1ec-84a9-409e-a871-0fcb0c3f6a4d)

**Comment by seveibar** [comment]
i think @ShiboSoftwareDev fixed this
