### ISSUE TITLE
Fix diode symbol with `up` `left` `right` `down`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#293]
/bounty $10

**Comment by seveibar** [comment]
@Abse2001

**Comment by developerfred** [comment]
/attrmpt #293 I will add new props ruler for direction on diode

**Comment by anas-sarkez** [comment]
@seveibar 
can you explain to me what is the problem?

![Image](https://github.com/user-attachments/assets/6a3f8f08-cea8-4061-bc6c-c57c4d0f8330)

**Comment by seveibar** [comment]
I think i already fixed this
