### ISSUE TITLE
Custom Footprints sometimes have an extra schematic pin

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#302]
pin5 in the schematic below

![Image](https://github.com/user-attachments/assets/af712f7f-4ecb-42c2-a556-1011752d097e)

Reproduction: https://tscircuit.com/editor?&snippet_type=package#data:application/gzip;base64,H4sIABSWNmcAA81WXW+bMBR951dYPEytlBKMCZAodJs6aZu0fkhbp01TVRlwGrpgW7ZRm0X577MNIaQfUrvuoX4gxufc63vuda4pK86EAiuQC4IVOZfkiOklSqgCazATrALuOyXzUuR1qYY5E8R1WiO15ERbaoOK0S94yWp1JhiXDxlyA7iOkzMqFeCl5mdkIUEKVg4w73ACfrnm1x0A9+PJB/di0ABBCwQG+H56/g12EGohZKHPJx0QtkC4sQkMtAZYAhuA45RUETHDOQFNyORWEVrIB8SY+CiuyARIJUp65awdh9zaBDRi3h9/hRDGl+gSaTl7VumkcbsP0kPrQBBVCwr29BSAaT4vuZ0BsPI8z1qs24UcF8esIIt0ZeyawbLrc7GYdO8AuHOl9C7DYWW4eUG9LtVezqohwXJJCnxpYTks2A1dMFy8reuySEniB2GEx2EMw3CUzbIIjTKShEniRzgIyBtO06MIJpFr0tkMwRRWJaOns5kkaqLLfjsB/gAs7fOPfoL1ls2ZLJ/KXm+Ud4ciXXXTDSZrzhclEWdYqJO6yojQrG2Crhc5zzNT9CZuew52nFeY1rrcugp9J6nbK57bUmeMKa4rrdLtBtNu8bBXhamsFMdFb8VIF+qT5un42vN8sYmhJeTZj9QNvHEwHo/GSTg2AwVVtdm/o/1M3YPA07RxZEl6wCi6S7wpCzU3Dq2nxp0Z8V3inJRXc5W60PMtntwlyDnmJHUFyVUfGD5Xsv6zvUCy//oFohcJbEoa++1APnr9isOHFR8gz9c7j3Qjac/nc2uKQpOD8DFhyBsZt8E/CisXv6W+2AjlWM137IXu70SL21nU7dg0qgPoRRCGfhxbVYkuqG1dWi0KosCPoNWaJHHSb3pP8LBxELS1h+EjDqCHEETJKGzyGvvxf7F/uYIneNg5Kb2CTIf3mmjDtJz9e/dqLcnu1Xr/E2WvRxhsL5B95y/nBgIX1wgAAA==

/bounty $20

**Comment by kom-senapati** [comment]
The code is giving some issues like
name prop is missing for chip 
Its not inside board
