### ISSUE TITLE
Don't wire through manufacturer labels in schematic

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#307]
This requires moving the manufacturer labels as a `schematic_text` core output, rather than inserting inside of `circuit-to-svg`

![Image](https://github.com/user-attachments/assets/f26b94d2-84c6-45d7-a7d2-5cd9f22c442e)

/bounty $30

**Comment by anas-sarkez** [comment]
@seveibar 
I've created a function that handles the chip manufacturer's label and chip name, and converts them into a `schematic-text` element. How can I modify the trace so it does not get passed to the `schematic-text`?
![Image](https://github.com/user-attachments/assets/ac1e3d18-ed8a-4b66-8344-d6506726fc14)

**Comment by seveibar** [comment]
Inside `Trace.ts` `schematic_text` will need to be added as an obstacle

**Comment by anas-sarkez** [comment]
@seveibar 
this is after added `schematic_text` to obstacle
![Image](https://github.com/user-attachments/assets/ef640154-7c4e-42d3-9406-947bd2b1c25c)

**Comment by seveibar** [comment]
nice that looks correct, the trace is no longer going through the schematic trace

**Comment by seveibar** [comment]
we should also make it not go through the symbol 🤔

**Comment by anas-sarkez** [comment]
> we should also make it not go through the symbol 🤔 (probably a separate PR i guess)

![Image](https://github.com/user-attachments/assets/362a0e5a-a593-4b0c-b6b5-0ecf8599b90f)
It's already added to obstacle
