### ISSUE TITLE
For schematic boxes that only have pins on the left and right, put the refdes in the top left and the manufacturer part number in the bottom left

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#324]
## Correct Placement

![Image](https://github.com/user-attachments/assets/a12e1b71-79d2-4359-b92b-a25a0eb98192)

## Incorrect Placement (current)

![Image](https://github.com/user-attachments/assets/33ab5578-f13d-4cf2-9f8e-522d0eafbc6a)

**Comment by anas-sarkez** [comment]
![Image](https://github.com/user-attachments/assets/a5135dcd-3cf7-4c87-9b06-f58660238a53)
@seveibar

**Comment by seveibar** [comment]
@anas-sarkez yep looks good!
