### ISSUE TITLE
Support Rotated Chips

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#331]
- [x] Requires: https://github.com/tscircuit/circuit-json/issues/66
- [x] Make sure that https://github.com/tscircuit/autorouting knows how to turn `rotated_rect` pads into an obstacle
- [x] Make sure `pcb-viewer` knows how to draw rotated rects
- [x] Compute the rotated rect when a rotation is not 90 degrees

Rotated rects should always be centered for ease-of-use, they should always rotate about the center.

You must have 3+ bounties to do this issue (it is not trivial)

/bounty $65

**Comment by ShiboSoftwareDev** [comment]
@seveibar what about a rotation prop for smtpads?

**Comment by ShiboSoftwareDev** [comment]
@seveibar what do you mean with the fourth point?

**Comment by seveibar** [comment]
@ShiboSoftwareDev yea not written well. That bullet point is basically saying "if a chip is rotated 45 degrees, make sure its smtpads all have the proper rotation

**Comment by ShiboSoftwareDev** [comment]
> [@ShiboSoftwareDev](https://github.com/ShiboSoftwareDev) yea not written well. That bullet point is basically saying "if a chip is rotated 45 degrees, make sure its smtpads all have the proper rotation

basically inherit rotation from chip

**Comment by ShiboSoftwareDev** [comment]
@seveibar how can I test the rotated rect on the autorouting repo? Also there are multiple autorouters, do I have to implement it on all of them seperately or try to create a global function, I haven't worked on that repo before and it's not super clear.

**Comment by seveibar** [comment]
@ShiboSoftwareDev theres a function called "getObstaclesFromSoup", i think the main goal is to create eg 3-5 rectangles approximating the rotated rect, that will fix all the autorouters

**Comment by seveibar** [comment]
@ShiboSoftwareDev this is an example of an approximation, the formula is incorrect however (doesn't properly cover at 80 degrees)

![Image](https://github.com/user-attachments/assets/55ee81ad-2dc5-4943-bec9-443798a12a9c)

```ts
const generateApproximatingRects = () => {
    const rects = [];
    const sliceWidth = width / numRects;
    
    for (let i = 0; i < numRects; i++) {
      const x = (i - numRects/2) * sliceWidth + sliceWidth/2;
      
      // Calculate offset based on rotation
      const rotatedX = x * cosAngle;
      const rotatedY = x * sinAngle;
      
      // Calculate the maximum height needed for full coverage at this slice
      // This is the sum of the vertical projections of both width and height
      const verticalProjectionFromWidth = Math.abs(sliceWidth * sinAngle);
      const verticalProjectionFromHeight = Math.abs(height * cosAngle);
      const sliceHeight = verticalProjectionFromWidth + verticalProjectionFromHeight;
      
      rects.push({
        x: centerX + rotatedX - sliceWidth/2,
        y: centerY + rotatedY - sliceHeight/2,
        width: sliceWidth,
        height: sliceHeight
      });
    }
    
    return rects;
  };
```

**Comment by seveibar** [comment]
For [tscircuit/checks](https://github.com/tscircuit/checks) we'll want to implement a "true collision check" rather than an approximation, but it's so much easier/faster to have upright rects in the autorouter in the short term that I think we should settle for the approximation. Future versions of the autorouter will do it properly. Note that we also approximate plated holes as rects right now
