### ISSUE TITLE
`getInheritedProperty` on `PrimitiveComponent`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#337]
This function should traverse upward until it finds the property defined in the `_parsedProps` of any component

```
<board minTraceWidth={0.2}>
  <group>
   <chip />
  </group>
</board>
```

For example if I do `chip.getInheritedProperty("minTraceWidth")` it will return the 0.2

**Comment by ShiboSoftwareDev** [comment]
@seveibar this method is already present in PrimitiveComponent class, did you mean to add it to NormalComponent?
![Image](https://github.com/user-attachments/assets/d77e6734-2d95-4b90-999b-f2f8994345db)

**Comment by Abse2001** [comment]
PR #339
