### ISSUE TITLE
Emit events and the start and end of rendering for every `Renderable`, send to root circuit

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#359]
Two main events:

- `renderable:renderLifecycle:<phase name>:start`
- `renderable:renderLifecycle:<phase name>:end`

e.g.

- `renderable:renderLifecycle:doInitialPcbComponentRender:start`
- `renderable:renderLifecycle:doInitialPcbComponentRender:end`

(the root circuit is the circuit defined in `Circuit.ts`, commonly used as `this.root`, all events from renderable are re-emitted)

The event payloads should include:

```js
{ renderId }
```

Create the utility event `"renderable:renderLifecycle:anyEvent"` to make it easier to listen to renderable events.

Make sure to test by recording all the events that are emitted using `circuit.on("renderable:anyEvent")

/bounty $30

**Comment by seveibar** [comment]
Looking good @anas-sarkez!!!!

**Comment by anas-sarkez** [comment]
![Image](https://github.com/user-attachments/assets/ded785b9-eb0f-4f44-a20f-e8371deef1e5)
