### ISSUE TITLE
Automatic schematic net labeling for passive-chip traces

### ISSUE THREAD

**Issue by seveibar** [tscircuit/core#387]
We have a trace with a passive on one side and a chip on the other side we it's eligible to be automatically turned into a net label style schematic trace it will be automatically converted if there are more than 5 complex trace elements: junction, crossings or turns

The net label to use is the label of the pin on the chip

e.g. C15 should "auto net label" to "ADC_VDDIO"

![Image](https://github.com/user-attachments/assets/ea6ef02c-c2e6-46ae-8970-0c5bb626b227)

/bounty $30

**Comment by AnasSarkiz** [comment]
![Image](https://github.com/user-attachments/assets/42837861-3d09-4dc9-97ac-1c3b3644f948)

**Comment by seveibar** [comment]
That looks right!!! @AnasSarkiz (nice!!!)

Can i make a small adjustment, can we make the netlabels have the refdes of the chip? So "U1_OUT1" instead of "OUT1"? Should help prevent "collisions"

Nicely done!

**Comment by AnasSarkiz** [comment]
@seveibar 

![Image](https://github.com/user-attachments/assets/a68b6fb8-56e6-4188-9cdd-7f3d65796cea)

**Comment by seveibar** [comment]
Looks good although im surprised some of the long traces for those resistors arent converting (maybe we need to tweak conditions? Maybe 4 turns should convert?

**Comment by AnasSarkiz** [comment]
How about a chip with four traces in the same face, and each trace has more than four turns? should we replace all of them with a netlabel? because I thought that we must have more than five traces on each face

**Comment by seveibar** [comment]
@AnasSarkiz lets not consider faces yet, im looking a bit closer and i think even traces with more than 5 turns arent getting converted right now (am i wrong)

Im not opposed to the face thing, but if we can keep it simple thats better

**Comment by seveibar** [comment]
Can i see it reduced to 4 turns? Maybe after we get that working we could do the face logic as an extension? Curious about the code complexity

**Comment by AnasSarkiz** [comment]
@seveibar I modified the logic if one of the condition get true `complex trace's index is >= 5 for on the same face` **or** `the trace has _countComplexElements >=4`  

Output

![Image](https://github.com/user-attachments/assets/b0cc3a95-e48c-4173-9256-ac4e182c970f)

![Image](https://github.com/user-attachments/assets/43a2e578-dd4d-42c1-9a37-fcca767f1b4c)

![Image](https://github.com/user-attachments/assets/282733f4-ab63-44bb-9526-2e0805308fc8)

![Image](https://github.com/user-attachments/assets/82ff9181-7f5f-4a76-a30a-5cb7b73d3a55)

**Comment by seveibar** [comment]
I think of we were to do an approach with sides, we would maybe decrease the allowed trace complexity of ours on a heavily populated side, but because of the relative complexity of that the customization parameters couldn't be as simple, so better to keep it simple with a single parameter for now

**Comment by AnasSarkiz** [comment]
it's my bad. I thought that we should have more than five complex traces on each side of a chip 
![Image](https://github.com/user-attachments/assets/2664cc33-bd25-468a-a4a3-f80b936e6fe0)

**Comment by AnasSarkiz** [comment]
![Image](https://github.com/user-attachments/assets/c8b110e1-410f-4de7-a977-e1f2a737efe4)
![Image](https://github.com/user-attachments/assets/a87fea6c-151c-4f91-8b37-a6ea5ef94ddb)
