### ISSUE TITLE
Missing silkscreen line component

### ISSUE THREAD

**Issue by RohittCodes** [tscircuit/core#410]
`SilkscreenLine` component is missing. required for https://github.com/tscircuit/pcb-viewer/issues/84

![Image](https://github.com/user-attachments/assets/8f04cdee-7b06-47ec-9ded-54e38d3d2150)

cc: @ShiboSoftwareDev

**Comment by ShiboSoftwareDev** [comment]
@seveibar

**Comment by seveibar** [comment]
@techmannih https://blog.tscircuit.com/p/getting-started-with-tscircuit-core

**Comment by RohittCodes** [comment]
maybe adding the manualEdits to the silkscreen line component for this issue will be the best.. 🤔
