### ISSUE TITLE
Create <Resonator />

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/core#426]
The resonator in our schematic symbol needs to be created with 3 pins. Take reference from how the `<Pinheader />` is implemented with multiple pins.

![Image](https://github.com/user-attachments/assets/c68fc8a6-0c02-44f8-bb32-c47effbef5b2)

**Comment by imrishabh18** [comment]
Yes! You will have to create the props in that repo

**Comment by imrishabh18** [comment]
No need to create an issue for this in props. Just directly create a PR for it, and Crystal props should be similar to the resonator

**Comment by imrishabh18** [comment]
Yes, you will have to add the `simple_resonator` in the source component of circuit json

**Comment by Anshgrover23** [comment]
@techmannih you are feel free to make PR on this one, as i am still working it won't be an issue
