### ISSUE TITLE
update all imports from @tscircuit/soup to circuit-json and remove the dependency

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/core#467]

**Comment by Anshgrover23** [comment]
@ShiboSoftwareDev yes must do things.

**Comment by seveibar** [comment]
@ShiboSoftwareDev it seems "@tscircuit/soup" isn't a dependency and isn't used anywhere (feel free to reopen if i'm incorrect, maybe this issue needs to be transferred somewhere)

**Comment by ShiboSoftwareDev** [comment]
@seveibar in a previous pr we removed an import from @tscircuit/soup, this means it was imported and it didn't cause issues because @tscircuit/soup is always in the node_modules because it wasn't removed from some repos

**Comment by seveibar** [comment]
Oooh i see 👍 @ShiboSoftwareDev
